apiVersion: V1
kind: Service
metadata:
  name: myjavaapp-svc
  labels:
    app: myjavaapp
spec:
  selector:
    app: myjavaapp
  type: NodePort
  ports:
  - port: 8080
    nodeport: 30001
    protocol: TCP
